# Generated by Django 6.0.5 on 2026-06-04 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TOP', 'Top / Shirt'), ('BOTTOM', 'Bottom / Pants'), ('FOOTWEAR', 'Footwear / Shoes'), ('OUTERWEAR', 'Outerwear / Coat / Blazer')], max_length=15)),
                ('color_category', models.CharField(choices=[('NEUTRAL', 'Neutral (Black, White, Grey, Navy)'), ('WARM', 'Warm (Red, Yellow, Brown, Beige)'), ('COOL', 'Cool (Blue, Green, Purple)')], max_length=15)),
                ('formality_level', models.IntegerField(choices=[(3, 'Sharp Corporate (Monday Style)'), (2, 'Smart Casual (Mid-Week Style)'), (1, 'Casual Professional (Friday Style)')])),
                ('weather_suitability', models.CharField(choices=[('SUNNY', 'Sunny / Hot'), ('RAINY', 'Rainy / Wet'), ('COLD', 'Cold / Chilly'), ('ALL', 'All-Weather / Versatile')], default='ALL', max_length=15)),
                ('in_laundry', models.BooleanField(default=False)),
                ('last_worn', models.DateField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
