# Generated by Django 6.0.5 on 2026-06-04 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='The Monday date representing this specific week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monday_weather', models.CharField(blank=True, default='Awaiting forecast...', max_length=100, null=True)),
                ('monday_confirmed', models.BooleanField(default=False)),
                ('tuesday_weather', models.CharField(blank=True, default='Awaiting forecast...', max_length=100, null=True)),
                ('tuesday_confirmed', models.BooleanField(default=False)),
                ('wednesday_weather', models.CharField(blank=True, default='Awaiting forecast...', max_length=100, null=True)),
                ('wednesday_confirmed', models.BooleanField(default=False)),
                ('thursday_weather', models.CharField(blank=True, default='Awaiting forecast...', max_length=100, null=True)),
                ('thursday_confirmed', models.BooleanField(default=False)),
                ('friday_weather', models.CharField(blank=True, default='Awaiting forecast...', max_length=100, null=True)),
                ('friday_confirmed', models.BooleanField(default=False)),
                ('friday_bottom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friday_bottoms', to='core.clothingitem')),
                ('friday_outerwear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friday_coats', to='core.clothingitem')),
                ('friday_shoes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friday_footwear', to='core.clothingitem')),
                ('friday_top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friday_tops', to='core.clothingitem')),
                ('monday_bottom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_bottoms', to='core.clothingitem')),
                ('monday_outerwear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_coats', to='core.clothingitem')),
                ('monday_shoes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_footwear', to='core.clothingitem')),
                ('monday_top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_tops', to='core.clothingitem')),
                ('thursday_bottom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday_bottoms', to='core.clothingitem')),
                ('thursday_outerwear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday_coats', to='core.clothingitem')),
                ('thursday_shoes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday_footwear', to='core.clothingitem')),
                ('thursday_top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday_tops', to='core.clothingitem')),
                ('tuesday_bottom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_bottoms', to='core.clothingitem')),
                ('tuesday_outerwear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_coats', to='core.clothingitem')),
                ('tuesday_shoes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_footwear', to='core.clothingitem')),
                ('tuesday_top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_tops', to='core.clothingitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
                ('wednesday_bottom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_bottoms', to='core.clothingitem')),
                ('wednesday_outerwear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_coats', to='core.clothingitem')),
                ('wednesday_shoes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_footwear', to='core.clothingitem')),
                ('wednesday_top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_tops', to='core.clothingitem')),
            ],
            options={
                'ordering': ['-week_start_date'],
                'unique_together': {('user', 'week_start_date')},
            },
        ),
    ]
