# Generated by Django 6.0.5 on 2026-06-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='closet_items/'),
        ),
    ]
